name: Pylint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install prospector[with_mypy] prospector[with_vulture] mypy vulture setuptools
        python3 -m pip install -r requirements.txt
    - name: Analysing the code with prospector
      run: rm upgrade_cache.py && prospector  --with-tool vulture  --with-tool mypy --strictness veryhigh --max-line-length 200
